// Strings for Panels context
export const PANEL_STRINGS = {
  OBJECTS_HEADER: '2 Objects',
  POLYGON_HEADER: '1 Polygon',
  MAPDATA_HEADER: '3 Map Data',
  TOOLS_HEADER: 'Tools',
  NO_OBJECTS: 'No objects added yet',
  NO_DATA: 'No data yet',
  SELECTED_OBJECT: 'Selected:',
  SELECTED_POLYGON: 'Selected:',
  ADD: 'Add',
  ON_MAP_INSTRUCTION: 'on map to place',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  CHOOSE_ICON: 'Choose Icon',
  SELECT_ICON: 'Select Icon',
  TOTAL_OBJECTS: 'Total objects:',
  TOTAL_POLYGONS: 'Total polygons:',
  SAVE: 'Save',
  SAVING: 'Saving...',
  DELETE_ALL_POLYGONS_CONFIRM: 'Delete all polygons? This action cannot be undone.',
  UNNAMED_POLYGON: 'Unnamed Polygon',
  TYPE: 'Type',
  NAME: 'Name',
  LAT: 'Lat',
  LNG: 'Lng',
  UNNAMED_OBJECT: 'Unnamed Object',
};
